import {useEffect,useRef,useState} from 'react';
import {RotateCcw} from 'lucide-react';
const names=['Pops','King','Loopy','Bana','Buzz','Berry','Pillow','Byte','Flaky','Scoops','Creamo'];
const image=(name:string)=>`/generated/mascots/${name.toLowerCase()}.webp`;
function shuffle<T,>(items:T[]):T[]{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function Memory({ar,onComplete}:{ar:boolean;onComplete?:()=>void}){
 const [cards,setCards]=useState(()=>shuffle([...names.slice(0,6),...names.slice(0,6)]));const [open,setOpen]=useState<number[]>([]);const [matched,setMatched]=useState<number[]>([]);const [moves,setMoves]=useState(0);
 useEffect(()=>{if(open.length!==2)return;const timer=setTimeout(()=>{if(cards[open[0]]===cards[open[1]])setMatched(m=>[...m,...open]);setOpen([]);},750);return()=>clearTimeout(timer);},[open,cards]);
 useEffect(()=>{if(matched.length===12)onComplete?.();},[matched.length,onComplete]);
 const reset=()=>{setCards(shuffle([...names.slice(0,6),...names.slice(0,6)]));setOpen([]);setMatched([]);setMoves(0);};
 return <><div className="game-heading"><div><h2>{ar?'طابق الشخصيات':'Match the mascots'}</h2><p>{ar?'اقلب ورقتين وابحث عن الأزواج الستة.':'Turn over two cards. Find all six matching pairs.'}</p></div><button className="game-reset" onClick={reset}><RotateCcw size={18}/>{ar?'من جديد':'Restart'}</button></div><p className="game-status" role="status">{matched.length===12?(ar?'رائع! وجدت كل الأزواج.':'Great matching! You found the whole crew.'):(ar?`${matched.length/2} من 6 أزواج · ${moves} محاولة`:`${matched.length/2} of 6 pairs · ${moves} moves`)}</p><div className="memory-grid">{cards.map((name,i)=>{const shown=open.includes(i)||matched.includes(i);return <button className={`memory-card ${shown?'revealed':''} ${matched.includes(i)?'matched':''}`} key={i} disabled={matched.includes(i)||open.includes(i)||open.length===2} aria-label={shown?name:(ar?`اقلب الورقة ${i+1}`:`Reveal card ${i+1}`)} onClick={()=>{setOpen(o=>[...o,i]);if(open.length===1)setMoves(m=>m+1);}}>{shown?<img src={image(name)} alt={name}/>:<span>?</span>}</button>})}</div></>;
}
export function Quiz({ar,onComplete}:{ar:boolean;onComplete?:()=>void}){
 const [order,setOrder]=useState(()=>shuffle(names));const [step,setStep]=useState(0);const [score,setScore]=useState(0);const [answer,setAnswer]=useState<string|null>(null);const [options,setOptions]=useState(()=>shuffle([order[0],...shuffle(names.filter(n=>n!==order[0])).slice(0,3)]));
 useEffect(()=>{if(step===names.length)onComplete?.();},[step,onComplete]);
 function reset(){const list=shuffle(names);setOrder(list);setStep(0);setScore(0);setAnswer(null);setOptions(shuffle([list[0],...shuffle(names.filter(n=>n!==list[0])).slice(0,3)]));}
 function next(){const s=step+1;setStep(s);setAnswer(null);if(s<names.length)setOptions(shuffle([order[s],...shuffle(names.filter(n=>n!==order[s])).slice(0,3)]));}
 return <><div className="game-heading"><div><h2>{ar?'من هذه الشخصية؟':'Who’s that Kiddo?'}</h2><p>{ar?'هل تعرف أسماء فريق كيدو؟':'How well do you know the crew?'}</p></div><button className="game-reset" onClick={reset}><RotateCcw size={18}/>{ar?'من جديد':'Restart'}</button></div>{step===names.length?<div className="quiz-finish"><img src={image('Pops')} alt="Pops"/><h3>{ar?'أحسنت!':'Nice work!'}</h3><p role="status">{score} / {names.length}</p><button className="kiddo-action kiddo-action-red" onClick={reset}>{ar?'العب مرة أخرى':'Play again'}</button></div>:<div className="quiz-round"><p className="game-status">{ar?`السؤال ${step+1} من ${names.length} · النقاط ${score}`:`Question ${step+1} of ${names.length} · Score ${score}`}</p><img className="quiz-mascot" src={image(order[step])} alt={ar?'شخصية كيدو المطلوب تخمين اسمها':'Kiddo mascot to identify'}/><div className="quiz-options">{options.map(n=><button key={n} disabled={answer!==null} className={`quiz-answer ${answer!==null&&n===order[step]?'correct':''} ${answer===n&&n!==order[step]?'incorrect':''}`} onClick={()=>{setAnswer(n);if(n===order[step])setScore(s=>s+1);}}>{n}</button>)}</div>{answer&&<div className="quiz-feedback"><p role="status">{answer===order[step]?(ar?'صحيح!':'You got it!'):(ar?`إنها ${order[step]}!`:`It’s ${order[step]}!`)}</p><button className="kiddo-action kiddo-action-red" onClick={next}>{ar?'التالي':'Next'}</button></div>}</div>}</>;
}
export function Catch({ar,onComplete}:{ar:boolean;onComplete?:()=>void}){
 const [running,setRunning]=useState(false);const [time,setTime]=useState(20);const [score,setScore]=useState(0);const [cell,setCell]=useState(4);const [started,setStarted]=useState(false);const board=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!running)return;const tick=setInterval(()=>setTime(t=>{if(t<=1){setRunning(false);return 0;}return t-1;}),1000);return()=>clearInterval(tick);},[running]);
 useEffect(()=>{if(!running)return;const tick=setInterval(()=>setCell(c=>(c+1+Math.floor(Math.random()*8))%9),1150);return()=>clearInterval(tick);},[running]);
 useEffect(()=>{if(started&&!running&&time===0&&score>0)onComplete?.();},[started,running,time,score,onComplete]);
 const start=()=>{setScore(0);setTime(20);setCell(Math.floor(Math.random()*9));setRunning(true);setStarted(true);setTimeout(()=>board.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus(),0);};
 return <><div className="game-heading"><div><h2>{ar?'التقط الحلقات':'Catch the crunch'}</h2><p>{ar?'اضغط على الحلقة قبل أن تتحرك. لديك 20 ثانية!':'Tap the cereal ring before it moves. You have 20 seconds!'}</p></div><button className="game-reset" onClick={start}><RotateCcw size={18}/>{ar?'ابدأ':'Start'}</button></div><p className="game-status" role="status">{ar?`${time} ثانية · ${score} نقطة`:`${time}s left · ${score} rings caught`}</p><div className="catch-grid" ref={board}>{Array.from({length:9},(_,i)=><button key={i} disabled={!running} aria-label={running&&i===cell?(ar?'التقط الحلقة':'Catch this ring'):(ar?`مكان فارغ ${i+1}`:`Empty spot ${i+1}`)} onClick={()=>{if(i===cell){setScore(s=>s+1);setCell(c=>(c+1+Math.floor(Math.random()*8))%9);}}}>{running&&i===cell?<span className="cereal-ring"/>:<span className="catch-dot"/>}</button>)}</div>{!running&&<div className="quiz-feedback"><p role="status">{started?(ar?`انتهى الوقت! التقطت ${score} حلقة.`:`Time’s up! You caught ${score} rings.`):(ar?'جاهز للتحدي؟':'Ready for a crunch challenge?')}</p><button className="kiddo-action kiddo-action-red" onClick={start}>{ar?'العب الآن':'Play now'}</button></div>}<p className="game-help">{ar?'على لوحة المفاتيح: استخدم Tab للتنقل وEnter لالتقاط الحلقة.':'Keyboard: use Tab to move between spots and Enter to catch a ring.'}</p></>;
}
